export interface MimeEntry {
  extension: string;
  mime: string;
  description: string;
}

export const MIME_DATA: MimeEntry[] = [
  // Text
  { extension: 'txt', mime: 'text/plain', description: 'Plain text' },
  { extension: 'html', mime: 'text/html', description: 'HTML document' },
  { extension: 'htm', mime: 'text/html', description: 'HTML document' },
  { extension: 'css', mime: 'text/css', description: 'Cascading Style Sheet' },
  { extension: 'csv', mime: 'text/csv', description: 'Comma-separated values' },
  { extension: 'ics', mime: 'text/calendar', description: 'iCalendar' },
  { extension: 'md', mime: 'text/markdown', description: 'Markdown' },
  { extension: 'xml', mime: 'text/xml', description: 'XML document' },
  { extension: 'rtf', mime: 'text/rtf', description: 'Rich Text Format' },
  { extension: 'vtt', mime: 'text/vtt', description: 'WebVTT subtitles' },
  { extension: 'srt', mime: 'application/x-subrip', description: 'SubRip subtitles' },
  // Application
  { extension: 'js', mime: 'application/javascript', description: 'JavaScript' },
  { extension: 'mjs', mime: 'application/javascript', description: 'JavaScript module' },
  { extension: 'json', mime: 'application/json', description: 'JSON data' },
  { extension: 'jsonld', mime: 'application/ld+json', description: 'JSON-LD' },
  { extension: 'pdf', mime: 'application/pdf', description: 'PDF document' },
  { extension: 'zip', mime: 'application/zip', description: 'ZIP archive' },
  { extension: 'gz', mime: 'application/gzip', description: 'Gzip archive' },
  { extension: 'tar', mime: 'application/x-tar', description: 'TAR archive' },
  { extension: '7z', mime: 'application/x-7z-compressed', description: '7-zip archive' },
  { extension: 'rar', mime: 'application/vnd.rar', description: 'RAR archive' },
  { extension: 'bz2', mime: 'application/x-bzip2', description: 'Bzip2 archive' },
  { extension: 'doc', mime: 'application/msword', description: 'Microsoft Word document' },
  { extension: 'docx', mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', description: 'Microsoft Word (OOXML)' },
  { extension: 'xls', mime: 'application/vnd.ms-excel', description: 'Microsoft Excel' },
  { extension: 'xlsx', mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', description: 'Microsoft Excel (OOXML)' },
  { extension: 'ppt', mime: 'application/vnd.ms-powerpoint', description: 'Microsoft PowerPoint' },
  { extension: 'pptx', mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', description: 'Microsoft PowerPoint (OOXML)' },
  { extension: 'odt', mime: 'application/vnd.oasis.opendocument.text', description: 'OpenDocument text' },
  { extension: 'ods', mime: 'application/vnd.oasis.opendocument.spreadsheet', description: 'OpenDocument spreadsheet' },
  { extension: 'odp', mime: 'application/vnd.oasis.opendocument.presentation', description: 'OpenDocument presentation' },
  { extension: 'wasm', mime: 'application/wasm', description: 'WebAssembly' },
  { extension: 'swf', mime: 'application/x-shockwave-flash', description: 'Adobe Flash' },
  { extension: 'apk', mime: 'application/vnd.android.package-archive', description: 'Android Package' },
  { extension: 'epub', mime: 'application/epub+zip', description: 'EPUB ebook' },
  { extension: 'sh', mime: 'application/x-sh', description: 'Shell script' },
  { extension: 'jar', mime: 'application/java-archive', description: 'Java archive' },
  { extension: 'war', mime: 'application/java-archive', description: 'Java web archive' },
  { extension: 'php', mime: 'application/x-httpd-php', description: 'PHP script' },
  { extension: 'sql', mime: 'application/sql', description: 'SQL script' },
  { extension: 'graphql', mime: 'application/graphql', description: 'GraphQL query' },
  { extension: 'proto', mime: 'application/protobuf', description: 'Protocol Buffers' },
  { extension: 'ttf', mime: 'font/ttf', description: 'TrueType font' },
  { extension: 'otf', mime: 'font/otf', description: 'OpenType font' },
  { extension: 'woff', mime: 'font/woff', description: 'Web Open Font Format' },
  { extension: 'woff2', mime: 'font/woff2', description: 'Web Open Font Format 2' },
  // Images
  { extension: 'png', mime: 'image/png', description: 'PNG image' },
  { extension: 'jpg', mime: 'image/jpeg', description: 'JPEG image' },
  { extension: 'jpeg', mime: 'image/jpeg', description: 'JPEG image' },
  { extension: 'gif', mime: 'image/gif', description: 'GIF image' },
  { extension: 'webp', mime: 'image/webp', description: 'WebP image' },
  { extension: 'avif', mime: 'image/avif', description: 'AVIF image' },
  { extension: 'svg', mime: 'image/svg+xml', description: 'SVG vector image' },
  { extension: 'ico', mime: 'image/x-icon', description: 'ICO icon' },
  { extension: 'bmp', mime: 'image/bmp', description: 'BMP image' },
  { extension: 'tiff', mime: 'image/tiff', description: 'TIFF image' },
  { extension: 'tif', mime: 'image/tiff', description: 'TIFF image' },
  { extension: 'heic', mime: 'image/heic', description: 'HEIC image (Apple)' },
  { extension: 'heif', mime: 'image/heif', description: 'HEIF image' },
  { extension: 'raw', mime: 'image/x-raw', description: 'Camera RAW image' },
  // Audio
  { extension: 'mp3', mime: 'audio/mpeg', description: 'MP3 audio' },
  { extension: 'wav', mime: 'audio/wav', description: 'WAV audio' },
  { extension: 'ogg', mime: 'audio/ogg', description: 'OGG audio' },
  { extension: 'flac', mime: 'audio/flac', description: 'FLAC lossless audio' },
  { extension: 'aac', mime: 'audio/aac', description: 'AAC audio' },
  { extension: 'opus', mime: 'audio/opus', description: 'Opus audio' },
  { extension: 'mid', mime: 'audio/midi', description: 'MIDI audio' },
  { extension: 'midi', mime: 'audio/midi', description: 'MIDI audio' },
  { extension: 'm4a', mime: 'audio/mp4', description: 'M4A audio' },
  { extension: 'wma', mime: 'audio/x-ms-wma', description: 'Windows Media Audio' },
  // Video
  { extension: 'mp4', mime: 'video/mp4', description: 'MP4 video' },
  { extension: 'webm', mime: 'video/webm', description: 'WebM video' },
  { extension: 'avi', mime: 'video/x-msvideo', description: 'AVI video' },
  { extension: 'mov', mime: 'video/quicktime', description: 'QuickTime video' },
  { extension: 'mkv', mime: 'video/x-matroska', description: 'Matroska video' },
  { extension: 'flv', mime: 'video/x-flv', description: 'Flash video' },
  { extension: 'wmv', mime: 'video/x-ms-wmv', description: 'Windows Media Video' },
  { extension: 'mpeg', mime: 'video/mpeg', description: 'MPEG video' },
  { extension: 'mpg', mime: 'video/mpeg', description: 'MPEG video' },
  { extension: 'ogv', mime: 'video/ogg', description: 'OGG video' },
  { extension: '3gp', mime: 'video/3gpp', description: '3GPP video' },
  { extension: 'ts', mime: 'video/mp2t', description: 'MPEG-TS video' },
  // Data formats
  { extension: 'yaml', mime: 'application/yaml', description: 'YAML' },
  { extension: 'yml', mime: 'application/yaml', description: 'YAML' },
  { extension: 'toml', mime: 'application/toml', description: 'TOML' },
  { extension: 'tsv', mime: 'text/tab-separated-values', description: 'Tab-separated values' },
  // Dev
  { extension: 'ts', mime: 'application/typescript', description: 'TypeScript' },
  { extension: 'py', mime: 'text/x-python', description: 'Python script' },
  { extension: 'rb', mime: 'text/x-ruby', description: 'Ruby script' },
  { extension: 'go', mime: 'text/x-go', description: 'Go source' },
  { extension: 'rs', mime: 'text/x-rust', description: 'Rust source' },
  { extension: 'java', mime: 'text/x-java-source', description: 'Java source' },
  { extension: 'c', mime: 'text/x-c', description: 'C source' },
  { extension: 'cpp', mime: 'text/x-c++src', description: 'C++ source' },
  { extension: 'h', mime: 'text/x-c', description: 'C header' },
  { extension: 'cs', mime: 'text/x-csharp', description: 'C# source' },
  { extension: 'swift', mime: 'text/x-swift', description: 'Swift source' },
  { extension: 'kt', mime: 'text/x-kotlin', description: 'Kotlin source' },
];
