// Major IANA timezone identifiers for the timezone converter tool.
export const MAJOR_TIMEZONES = [
  { id: 'UTC', label: 'UTC (UTC+0)' },
  { id: 'America/New_York', label: 'New York (ET)' },
  { id: 'America/Chicago', label: 'Chicago (CT)' },
  { id: 'America/Denver', label: 'Denver (MT)' },
  { id: 'America/Los_Angeles', label: 'Los Angeles (PT)' },
  { id: 'America/Anchorage', label: 'Anchorage (AKT)' },
  { id: 'Pacific/Honolulu', label: 'Honolulu (HT)' },
  { id: 'America/Sao_Paulo', label: 'São Paulo (BRT)' },
  { id: 'America/Buenos_Aires', label: 'Buenos Aires (ART)' },
  { id: 'America/Mexico_City', label: 'Mexico City (CST)' },
  { id: 'America/Toronto', label: 'Toronto (ET)' },
  { id: 'America/Vancouver', label: 'Vancouver (PT)' },
  { id: 'Europe/London', label: 'London (GMT/BST)' },
  { id: 'Europe/Paris', label: 'Paris (CET/CEST)' },
  { id: 'Europe/Berlin', label: 'Berlin (CET/CEST)' },
  { id: 'Europe/Moscow', label: 'Moscow (MSK)' },
  { id: 'Europe/Istanbul', label: 'Istanbul (TRT)' },
  { id: 'Europe/Rome', label: 'Rome (CET/CEST)' },
  { id: 'Europe/Madrid', label: 'Madrid (CET/CEST)' },
  { id: 'Europe/Amsterdam', label: 'Amsterdam (CET/CEST)' },
  { id: 'Europe/Warsaw', label: 'Warsaw (CET/CEST)' },
  { id: 'Europe/Stockholm', label: 'Stockholm (CET/CEST)' },
  { id: 'Europe/Athens', label: 'Athens (EET/EEST)' },
  { id: 'Africa/Cairo', label: 'Cairo (EET)' },
  { id: 'Africa/Lagos', label: 'Lagos (WAT)' },
  { id: 'Africa/Johannesburg', label: 'Johannesburg (SAST)' },
  { id: 'Africa/Nairobi', label: 'Nairobi (EAT)' },
  { id: 'Asia/Dubai', label: 'Dubai (GST)' },
  { id: 'Asia/Karachi', label: 'Karachi (PKT)' },
  { id: 'Asia/Kolkata', label: 'Kolkata (IST)' },
  { id: 'Asia/Dhaka', label: 'Dhaka (BST)' },
  { id: 'Asia/Bangkok', label: 'Bangkok (ICT)' },
  { id: 'Asia/Singapore', label: 'Singapore (SGT)' },
  { id: 'Asia/Shanghai', label: 'Shanghai (CST)' },
  { id: 'Asia/Tokyo', label: 'Tokyo (JST)' },
  { id: 'Asia/Seoul', label: 'Seoul (KST)' },
  { id: 'Asia/Jakarta', label: 'Jakarta (WIB)' },
  { id: 'Asia/Taipei', label: 'Taipei (CST)' },
  { id: 'Asia/Hong_Kong', label: 'Hong Kong (HKT)' },
  { id: 'Asia/Tehran', label: 'Tehran (IRST)' },
  { id: 'Asia/Riyadh', label: 'Riyadh (AST)' },
  { id: 'Asia/Tashkent', label: 'Tashkent (UZT)' },
  { id: 'Australia/Sydney', label: 'Sydney (AEST/AEDT)' },
  { id: 'Australia/Melbourne', label: 'Melbourne (AEST/AEDT)' },
  { id: 'Australia/Perth', label: 'Perth (AWST)' },
  { id: 'Pacific/Auckland', label: 'Auckland (NZST/NZDT)' },
  { id: 'Pacific/Fiji', label: 'Fiji (FJT)' },
];
