// Tool manifest — import each tool module to trigger side-effect registration.
// Agent 0 (scaffold): all sections are stubs. Tool agents fill these in.

// === Video/GIF/Audio tools (Agent 1) ===
// import './video/video-convert';
// import './video/video-to-gif';
// import './video/video-extract-frames';
// import './video/video-trim';
// import './video/video-compress';
// import './video/video-screenshot';
// import './video/video-speed';
// import './video/video-reverse';
// import './video/video-add-subtitle';
// import './video/video-extract-audio';
// import './gif/gif-make';
// import './gif/gif-extract-frames';
// import './gif/gif-optimize';
// import './gif/gif-reverse';
// import './gif/gif-speed';
// import './gif/gif-crop';
// import './audio/audio-convert';
// import './audio/audio-trim';
// import './audio/audio-merge';
// import './audio/audio-normalize';
// import './audio/audio-speed';
// import './audio/audio-id3';

// === Image/PDF tools (Agent 2) ===
import './image/image-convert';
import './image/image-compress';
import './image/image-resize';
import './image/image-rotate-flip';
import './image/image-crop';
import './image/image-exif';
import './image/image-to-base64';
import './image/base64-to-image';
import './image/favicon-gen';
import './image/svg-optimize';
import './image/qr-generate';
import './image/qr-decode';
import './image/barcode-generate';
import './image/color-pick';
import './image/palette-extract';
import './image/placeholder-gen';
import './image/image-diff';
import './image/sprite-sheet';
import './pdf/pdf-merge';
import './pdf/pdf-split';
import './pdf/pdf-extract-pages';
import './pdf/pdf-compress';
import './pdf/pdf-to-images';
import './pdf/images-to-pdf';
import './pdf/pdf-rotate';
import './pdf/pdf-extract-text';
import './pdf/pdf-metadata';
import './pdf/pdf-watermark';
import './pdf/pdf-page-numbers';
import './pdf/pdf-protect';

// === Data/Text tools (Agent 3) ===
// import './data/json-format';
// import './data/json-to-yaml';
// import './data/yaml-to-json';
// import './data/json-to-toml';
// import './data/toml-to-json';
// import './data/csv-to-json';
// import './data/json-to-csv';
// import './data/xml-to-json';
// import './data/json-to-xml';
// import './data/json-query';
// import './data/csv-viewer';
// import './data/sql-format';
// import './data/protobuf-decode';
// import './text/base64';
// import './text/url-encode';
// import './text/html-encode';
// import './text/case-convert';
// import './text/text-diff';
// import './text/markdown-preview';
// import './text/html-to-markdown';
// import './text/regex-tester';
// import './text/text-stats';
// import './text/text-sort';
// import './text/lorem-ipsum';
// import './text/unicode-inspect';
// import './text/string-escape';
// import './text/line-tools';

// === Crypto/Network/Developer tools (Agent 4) ===
// import './crypto/hash';
// import './crypto/hmac';
// import './crypto/aes';
// import './crypto/rsa-keygen';
// import './crypto/pgp-encrypt';
// import './crypto/pgp-decrypt';
// import './crypto/bcrypt';
// import './crypto/jwt-decode';
// import './crypto/totp';
// import './crypto/password-gen';
// import './crypto/password-strength';
// import './network/ip-info';
// import './network/dns-lookup';
// import './network/http-headers';
// import './network/whois';
// import './network/ping';
// import './network/url-parse';
// import './network/cors-test';
// import './developer/json-schema';
// import './developer/cron-parse';
// import './developer/color-convert';
// import './developer/uuid-gen';
// import './developer/fake-data';
// import './developer/number-base';
// import './developer/timestamp';
// import './developer/mime-lookup';
// import './developer/jwt-sign';

// === Math/Misc tools (Agent 5) ===
// import './math/calculator';
// import './math/matrix';
// import './math/stats';
// import './math/unit-convert';
// import './math/roman-numeral';
// import './math/prime';
// import './misc/zip-create';
// import './misc/zip-extract';
// import './misc/file-hash';
// import './misc/font-preview';
// import './misc/color-picker';
// import './misc/stopwatch';
